import java.util.regex.Pattern

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    dependencies {
        classpath 'com.sensorsdata.analytics.android:android-gradle-plugin2:3.5.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
    }
    def dir = new File(rootDir, "plugin-resp")
    if (dir.exists()) {
        repositories {
            maven {
                url dir.toURI()
            }
        }
        dependencies {
            classpath("com.mercer:magician:1.0.0")
        }
    } else {
        System.err.println("本地插件仓库不存在.")
    }
}

plugins {
    id 'com.android.application' version '7.4.2' apply false
    id 'com.android.library' version '7.4.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.0' apply false
    id 'cn.therouter' version '1.2.0' apply false
    id 'com.google.gms.google-services' version "4.4.2" apply false
    id 'com.google.devtools.ksp' version "1.9.0-1.0.13" apply false
    id 'org.jetbrains.kotlin.jvm' version "1.9.0" apply false
    // id("dependency-reuse") apply(true)
}
// 根据此文件判定当前是否在开发人员本地
def localFile = rootProject.file("local.properties")
ext {
    debugCommonMoudle = false
    debugModule = false
    isLocal = localFile.exists()
}

task clean(type: Delete) {
    delete rootProject.buildDir
    delete(new File(rootDir, "local-repo"))
    delete(new File(rootDir, "repo"))
    delete(new File(rootDir, "resp"))
}


def dir = new File(rootDir, "plugin-resp")
if (dir.exists()) {
    apply plugin: "dependency-reuse"
    Properties localProperties = getLocalProperties()
    def isEnabled = Boolean.parseBoolean(localProperties.get("use.dependency.reuse"))
    dependencyReuse {
        respUri = new File(rootDir, "repo").toURI()
        groupId = "com.mercer"
        enabled = true
        autoPublish = true
    }
}

Properties getLocalProperties() {
    def properties = new Properties()
    def file = new File(rootDir, "local.properties")
    println(file.absolutePath)
    properties.load(file.newInputStream())
    return properties
}

// 本地仓库路径
def repoFolder = rootProject.file("resp")
// 本地依赖 groupId
def group = "com.aiper"

ext.repo = repoFolder
ext.groupId = group

/*
if (project.file("local.properties").exists()) {
    def taskNames = gradle.startParameter.taskNames
    println("running the Gradle command >>>${taskNames}")
    tasks.register('deleteRepo', Delete) {
        delete repoFolder
    }
    Pattern pattern = Pattern.compile(":?[a-zA-Z0-9]+:assemble(debug|trial|release)")
    // 检测是否为打包安装的任务
    var condition = taskNames.size() == 1 && pattern.matcher(taskNames.first().toLowerCase()) != null
    if (!condition) {
        return
    }
    if (repoFolder.exists()) {
        // 所有子模块
        Set<Project> children = project.subprojects
        // 已发布缓存
        Set<String> includes = new HashSet<>()
        // 未发布缓存
        Set<String> excludes = new HashSet<>()
        File folder = new File(repoFolder, group.replace(".", "/"))
        // TODO: 暂拟定版本号为 1.0.0,不变
        def version = "1.0.0"
        for (child in children) {
            // TODO: 暂不考虑 子模块导入的插件类型
            // TODO: 暂不考虑 不完整 的情况
            def buildFileExists = child.buildFile.exists()
            if (!buildFileExists) {
                continue
            }
            List<String> names = new ArrayList()
            Project level = child
            do {
                names.add(0, level.name)
                level = level.parent
            } while (level != rootProject)
            def name = names.join("_")
            def f = new File(folder, "${name}/$version")
            if (f.exists()) {
                includes.add(name)
            } else {
                excludes.add(name)
            }
        }
        subprojects {
            configurations.configureEach {
                resolutionStrategy {
                    dependencySubstitution {
                        for (def value in includes) {
                            def target = "$group:$value:$version"
                            substitute project(":${value.split('_').join(':')}") using module(target)
                        }
                        for (def value in excludes) {
                            def target = "$group:$value:$version"
                            substitute module(target) using project(":${value.replace('_', ':')}")
                        }
                    }
                }
            }
        }
    }
}
*/