pluginManagement {
    // includeBuild("magician")
    repositories {
        google()
        mavenCentral()
        jcenter()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.google.com' }
        maven { url "https://maven.aliyun.com/repository/public" }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url new File(rootDir, "repo").toURI() }
        maven { url new File(rootDir, "resp").toURI() }
        google()
        mavenCentral()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.google.com' }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url 'https://maven-other.tuya.com/repository/maven-releases/' }
        maven { url "https://maven-other.tuya.com/repository/maven-commercial-releases/" }
    }
}
rootProject.name = "Aiper"

include ':app'

include ':base:base'
include ':base:common-ui'

include ':common-service:device-api'
include ':common-service:database'

include ':features:ymodem'
include ':features:dev'
include ':features:weather'

include ':business:device-s'
include ':business:device-x'
include ':business:device-common'
include ':business:device-r'
include ':business:sobot-chat'
include ':business:customer'
include ':business:mine'
include ':business:device-i'
include ':business:device-hydrocomm'

//include ':magician'
