import java.text.SimpleDateFormat

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
    id 'therouter'
    id 'com.google.gms.google-services'
    // id 'com.sensorsdata.analytics.android'
    id 'com.google.firebase.crashlytics'
    id 'com.google.devtools.ksp'
}

if (!isLocal) {
    apply plugin: "com.sensorsdata.analytics.android"
}

android {
    signingConfigs {
        release {
            storeFile file('../aiper.jks')
            storePassword 'Aiper#2023'
            keyAlias 'aiper'
            keyPassword 'Aiper#2023'
        }
    }
    namespace 'com.aiper.link'
    compileSdk 34

    defaultConfig {
        applicationId "com.aiper.link"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            minifyEnabled !isLocal
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseCrashlytics {
                mappingFileUploadEnabled = false
            }
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseCrashlytics {
                mappingFileUploadEnabled = false
            }
        }
    }
    flavorDimensions = ["environment"]
    def time = currentTime()
    def branch = currentBranch()
    productFlavors {
        dev {
            dimension("environment")
            applicationIdSuffix ".debug"
            resValue "string", "app_name", "Aiper_develop"
            buildConfigField "String", "ENVIRONMENT", "\"dev\""
            buildConfigField "String", "VERSION_SUFFIX", "\".${time}${branch}_dev\""
            buildConfigField "String", "URL_SENSORSDATA", "\"http://10.10.0.202:30092\""
        }
        trial {
            dimension("environment")
            applicationIdSuffix ".test"
            resValue "string", "app_name", "Aiper_internal"
            buildConfigField "String", "ENVIRONMENT", "\"test\""
            buildConfigField "String", "VERSION_SUFFIX", "\".${time}_test\""
            buildConfigField "String", "URL_SENSORSDATA", "\"http://13.229.121.202:30098\""
        }
        product {
            dimension("environment")
            resValue "string", "app_name", "Aiper"
            buildConfigField "String", "ENVIRONMENT", "\"product\""
            buildConfigField "String", "VERSION_SUFFIX", "\"\""
            buildConfigField "String", "URL_SENSORSDATA", "\"https://event-tracking.aiper.com/new\""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        dataBinding true
        buildConfig true
        viewBinding true
    }

    variantFilter { variant ->
        if (variant.buildType.name == 'release') {
            variant.getFlavors().each() { flavor ->
                if (flavor.name == 'dev') {
                    variant.setIgnore(true)
                }
            }
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    testOptions {
        unitTests.all {
            it.enabled = false
        }
    }
}

dependencies {
    implementation project(path: ':base:base')
    implementation project(path: ':business:device-s')
    implementation project(path: ':business:device-common')
    implementation project(path: ':common-service:device-api')
    if (!debugModule) {
        implementation project(path: ':business:device-x')
    }
    if (!debugModule) {
        implementation project(path: ':business:device-r')
    }
    if (!debugModule) {
        implementation(project(':business:customer'))
        implementation(project(':business:mine'))
        implementation project(':business:device-i')
    }
    if (!debugModule) {
        implementation project(path: ':business:device-i')
    }
    if (!debugModule) {
        implementation project(path: ':business:device-i')
    }

    //基站
    implementation(project(":business:device-hydrocomm"))
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout

    def room_version = "2.5.1"
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation files('libs/pinyin4j-2.5.0.jar')
    implementation("cn.therouter:router:1.2.1")
    kapt("cn.therouter:apt:1.2.1")
    //firebase消息推送
    implementation(platform("com.google.firebase:firebase-bom:32.3.1"))
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation("com.google.firebase:firebase-analytics-ktx")
    implementation('com.google.firebase:firebase-messaging')


    implementation 'com.sobot.chat:sobotsupport-glidev4:2.3'
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.4.0-release-jitpack'
    implementation 'com.jsibbold:zoomage:1.3.1'
    implementation "androidx.work:work-runtime-ktx:2.7.0"

    implementation 'com.github.yellowcath:VideoProcessor:2.4.2'
    implementation project(path: ':common-service:device-api')
    implementation(project(":common-service:database"))
    implementation(project(':business:sobot-chat'))
    // 客服
    // implementation project(':base:sobotsdk-x')
    implementation project(':base:common-ui')
    implementation("androidx.paging:paging-common-ktx:3.3.0")
    implementation("androidx.paging:paging-runtime-ktx:3.3.0")
    // 屏幕视频
    implementation("com.github.JessYanCoding:AndroidAutoSize:v1.2.1")
    implementation(project(':features:weather'))

    // 本地打包时才引入 LeakCanary，避免影响每日构建包测试
    if (isLocal) {
        debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.12'
        debugImplementation 'com.squareup.leakcanary:leakcanary-android-process:2.9.1'
    }

    /*
    implementation("com.github.luhaibing.chestnuts:core:1.2")
    ksp("com.github.luhaibing.chestnuts:processor:1.2")
    */
    implementation(libs.chestnuts.core)
    ksp(libs.chestnuts.processor)

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

}

static String currentTime() {
    def date = new Date()
    def sdf = new SimpleDateFormat("MMddHHmm")
    sdf.setTimeZone(TimeZone.getTimeZone("GMT+8"))
    return sdf.format(date)
}

static String currentBranch() {
    try {
        def branch = 'git rev-parse --abbrev-ref HEAD'.execute().text.trim()
        return "_$branch"
    } catch (Exception e) {
        println "无法获取Git分支: ${e.message}"
        return ""
    }
}