plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
    id 'com.sensorsdata.analytics.android'
    id "com.google.protobuf" version "0.9.4"
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.serialization' version '2.0.21'
}

android {
    namespace 'com.aiper.base'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += ['-Xcontext-receivers']
    }
    buildFeatures {
        dataBinding true
        buildConfig true
    }
    sourceSets {
        main {
            main.res.srcDirs += "src/main/customers-res"
            main.res.srcDirs += "src/main/tools-res"
        }
    }
}

dependencies {
    api 'androidx.core:core-ktx:1.10.1'
    api 'androidx.appcompat:appcompat:1.6.1'
    api 'com.google.android.material:material:1.8.0'
    api 'androidx.constraintlayout:constraintlayout:2.1.4'
    api 'com.google.protobuf:protobuf-java:3.24.4'
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    def coroutines_version = '1.6.4'
    api "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines_version"
    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
    api("org.jetbrains.kotlin:kotlin-reflect:1.8.0")
    def okhttp_version = '5.0.0-alpha.10'
    api "com.squareup.okhttp3:okhttp:$okhttp_version"
    api "com.squareup.okhttp3:logging-interceptor:$okhttp_version"
    def retrofit_version = "2.9.0"
    api "com.squareup.retrofit2:retrofit:$retrofit_version"
    api "com.squareup.retrofit2:converter-gson:$retrofit_version"
    def lifecycle_version = "2.7.0"
    api "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    api "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    api "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    def nav_version = "2.8.5"
    api "androidx.navigation:navigation-fragment-ktx:$nav_version"
    api "androidx.navigation:navigation-ui-ktx:$nav_version"
    api "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
    api 'com.blankj:utilcodex:1.31.0'// 工具包 pt适配
    api 'com.github.getActivity:MultiLanguages:8.0' // 多语言适配
    api 'com.geyifeng.immersionbar:immersionbar:3.2.2'// 基础依赖包，必须要依赖
    api 'com.geyifeng.immersionbar:immersionbar-ktx:3.2.2'// kotlin扩展
    api 'io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.9'//适配器
    api 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.2'//上下拉刷新
    implementation("androidx.legacy:legacy-support-v4:1.0.0")
    api "com.github.bumptech.glide:glide:4.15.1"
    kapt 'com.github.bumptech.glide:compiler:4.15.1'
    def room_version = "2.4.2"
    kapt "androidx.room:room-compiler:$room_version"
    def luck_version = "v3.11.1"
    api "io.github.lucksiege:pictureselector:$luck_version"
    api "io.github.lucksiege:compress:$luck_version"
    api "io.github.lucksiege:ucrop:$luck_version"
    api 'com.amazonaws:aws-android-sdk-s3:2.73.0'// 亚马逊文件上传库
    api 'com.airbnb.android:lottie:6.4.0'
    api 'com.github.zcweng:switch-button:0.0.3@aar'//开关按钮
    kapt "cn.therouter:apt:1.2.1"
    api "cn.therouter:router:1.2.1"
    api 'org.greenrobot:eventbus:3.3.1'//事件分发
    api 'com.amazonaws:aws-android-sdk-iot:2.73.0'
    api 'com.amazonaws:aws-android-sdk-cognito:2.20.1'
    api 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.73.0'
//    api 'com.amazonaws:aws-android-sdk-mobile-client:2.73.0'

    api 'com.github.DylanCaiCoding.LoadingStateView:loadingstateview-ktx:4.1.0'
    api("com.github.DylanCaiCoding:MultiBaseUrls:1.0.0")
    api('com.github.DylanCaiCoding:MMKV-KTX:2.0.1') {
        exclude(group: "com.tencent", module: "mmkv-static")
    }
    // https://mvnrepository.com/artifact/com.tencent/mmkv-static
    api("com.tencent:mmkv-static:1.3.9")

    api 'com.sensorsdata.analytics.android:SensorsAnalyticsSDK:6.8.0'

    api "androidx.camera:camera-camera2:1.2.2"
    api "androidx.camera:camera-lifecycle:1.2.2"
    api "androidx.camera:camera-view:1.2.2"
    api 'com.google.mlkit:barcode-scanning:17.2.0'
    api 'no.nordicsemi.android:ble-ktx:2.9.0'
    api 'no.nordicsemi.android.support.v18:scanner:1.6.0'
    api 'com.jakewharton:process-phoenix:2.1.2'

    // 监听网络请求
    implementation 'com.localebro:okhttpprofiler:1.0.8'

    //datastore
    implementation "androidx.datastore:datastore:1.0.0"
    implementation("androidx.datastore:datastore-preferences:1.0.0")
    // https://mvnrepository.com/artifact/com.google.protobuf/protobuf-javalite
    // implementation("com.google.protobuf:protobuf-javalite:3.25.3")
    // implementation("com.google.protobuf:protobuf-javalite:3.24.4")
    implementation("com.google.protobuf:protobuf-java:3.24.4")
    // implementation("com.google.protobuf:protobuf-javalite:3.19.4")

    // https://mvnrepository.com/artifact/com.github.bumptech.glide/okhttp4-integration
    // implementation("com.github.bumptech.glide:okhttp4-integration:4.16.0")

    implementation("androidx.work:work-runtime-ktx:2.9.0")

    implementation(project(':base:common-ui'))
    api("com.github.JessYanCoding:AndroidAutoSize:v1.2.1")
    api("androidx.window:window:1.3.0")

    api 'com.kizitonwose.calendar:view:2.5.4'

    api 'com.github.yyued:SVGAPlayer-Android:2.6.1'
    def media3_version = "1.4.1"
    api "androidx.media3:media3-exoplayer:$media3_version"
    api "androidx.media3:media3-ui:$media3_version"
    api "androidx.media3:media3-common:$media3_version"

    /*
    implementation("com.github.luhaibing.chestnuts:core:1.2")
    ksp("com.github.luhaibing.chestnuts:processor:1.2")
    */
    implementation(libs.chestnuts.core)
    ksp(libs.chestnuts.processor)

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

}

protobuf {
    protoc {
        // artifact = "com.google.protobuf:protoc:3.19.4"
        // artifact = "com.google.protobuf:protoc:3.25.3"
        artifact = "com.google.protobuf:protoc:3.24.4"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option 'lite'
                }
            }
        }
    }
}